### ISSUE TITLE
InventorySample doesn't get past the splashscreen

### ISSUE THREAD

**Issue by rickengle** [Microsoft/InventorySample#24]
After downloading the InventorySample zip and running it locally under Visual Studio 2017, the splash screen comes up but never proceeds.   I did have to set the startup project from Inventory.ViewModels as that project isn't a valid start project.  Any idea what's wrong?

**Comment by Alvaromah** [comment]
You have to set the startup project to the Inventory.App and the solution platform to x86.
When the application starts for the first time, it may take some time to download the database from the 
internet.
Please, let me know if this helps.

**Comment by Alvaromah** [comment]
@rickengle Adding a progress bar could be a good solution.
Thanks for your feedback.

**Comment by Alvaromah** [comment]
Implemented in pull request by @dishantmshah.
