### ISSUE TITLE
Layout issue in compact view

### ISSUE THREAD

**Issue by rickengle** [Microsoft/InventorySample#25]
Hi when running the Inventory app when you shrink the width to its most compact size, the Hamburger menu overlays the Dashboard label (Texkblock?).   Possibly you can shift the page content down by one line so that it there isn't any UI overlap.

Thanks,
 Rick

**Comment by Alvaromah** [comment]
@rickengle Thanks for reporting. Labeled as a bug.

**Comment by Alvaromah** [comment]
Closed with pull request by @dishantmshah
