### ISSUE TITLE
Missing 'PaneToggleButtonSize' resource

### ISSUE THREAD

**Issue by ComponentFactory** [Microsoft/InventorySample#27]
Downloading and running on 1803 with Visual Studio 15.7.1 for the x64 target causes a crash as soon as you login as the default user. 

There are three places in XAML that expect a static resource called **PaneToggleButtonSize**. Unfortunately this resource is not defined. 

I replaced it with the constant value of 32 and it allows the application to run.

**Comment by Alvaromah** [comment]
Thanks for reporting!

It seems like this property is not defined in some versions of generic.xaml.
To avoid this problem we will fix it with a constant value.
Please, note that the real value is 48 not 32.

Regards,

Alvaro

**Comment by Alvaromah** [comment]
Fixed in commit #169
