### ISSUE TITLE
Can't build Inventory.App

### ISSUE THREAD

**Issue by keiokuma** [Microsoft/InventorySample#30]
I downloaded sample of this site. I can build Inventory.Data  and Inventory.ViewModels.
But cannot build Inventory.App. There is two build errors as follows :  
------------------------------------------------------    
1.Cannot resolve Assembly or Windows Metadata file 'Type universe cannot resolve assembly: System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a.'	Inventory.App	C:\Users\homepc\Downloads\InventorySample-master\src\Inventory.App\Inventory.App.csproj
------------------------------------------------------    
2.CS2001 could not find file 'C:\Users\homepc\Downloads\InventorySample-master\src\Inventory.App\obj\x86\Debug\App.g.i.cs'	Inventory.App	C:\Users\homepc\Downloads\InventorySample-master\src\Inventory.App\CSC
------------------------------------------------------    
I think that No1 Error will be clear to repair csproj file. but I don't know where to change a section.  
No2 Error is App partial class App.g.i.cs was not made by build process. It may be effective that change vs2015 or change build target. Who knows to solve two problems. Please help.

my  environment:  

 Visual Studio2017 v15.7.1  

 Win10Pro  

 .NET Framework 4.7.03056

**Comment by codingdna2** [comment]
I've just built the project with no issue. I've the same environment as you do (VS2017 15.7.4).

You may want to check if the NuGet packages were restored correctly. You can force manually Right clicking on the Solution and selecting "Restore Nuget Packages".

**Comment by keiokuma** [comment]
My Inventory.App could be built and run by your advice that selecting Restore NuGet Package. I'm very much thank you to your help. many thanks.
