### ISSUE TITLE
How to add a dbset using the code first entity frameworks?

### ISSUE THREAD

**Issue by phanchaulong** [microsoft/InventorySample#35]
How to add a dbset using the code first entity frameworks in this project?
please help me.
Thanks so much

**Comment by codingdna2** [comment]
1. Add the entities to the Inventory.Data project (folder Data). Check the existing ones to see how the mapping works.
2. Modify the DataService accordingly, adding your methods to query/update the entity (IDataService interface and DataServiceBase class)
3. Use it in your service class (see folder Services inside main project)
Regards
