### ISSUE TITLE
Documentation Issues

### ISSUE THREAD

**Issue by Meister1867** [microsoft/InventorySample#48]
I'm trying to learn from some of this great coding, so I keep reading the documentation.  Just a few notes:

https://github.com/Microsoft/InventorySample/blob/master/docs/Architecture/Overview.md
"VanArsdel Inventory Sample is based on a VMMV architecture pattern"  
Shouldn't it be MVVM?

"use the LogService implementation as a singletonok. This"
Shouldn't it be singleton?

https://github.com/Microsoft/InventorySample/tree/master/docs/DataAccess
"and we are usnig Entity Framework"
should be "using"

**Comment by marb2000** [comment]
Thank you so much for finding these typos.
