### ISSUE TITLE
New UX Design Suggestion

### ISSUE THREAD

**Issue by jaenfourie** [microsoft/InventorySample#53]
![inventory_wireframes](https://user-images.githubusercontent.com/14773203/58694419-3e4a5200-8393-11e9-9ba6-a09393102330.png)
![Orders](https://user-images.githubusercontent.com/14773203/58694444-47d3ba00-8393-11e9-8616-5f0746c95127.png)
![Addproduct](https://user-images.githubusercontent.com/14773203/58694446-486c5080-8393-11e9-8f21-005167f69b9b.png)
![customers](https://user-images.githubusercontent.com/14773203/58694447-486c5080-8393-11e9-9183-1381c7b85a2a.png)
![expanded](https://user-images.githubusercontent.com/14773203/58694448-486c5080-8393-11e9-8ae1-6cec0cc6c1ca.png)
![Inventory](https://user-images.githubusercontent.com/14773203/58694450-4904e700-8393-11e9-8317-6a1c02b4f32b.png)
![transient](https://user-images.githubusercontent.com/14773203/58694455-4c986e00-8393-11e9-8ed1-cd950087a3c6.png)
![wf_products](https://user-images.githubusercontent.com/14773203/58694465-54581280-8393-11e9-974d-e19c2d69684c.png)
![wf_add-product](https://user-images.githubusercontent.com/14773203/58694468-54f0a900-8393-11e9-93be-de2261ffc62a.png)
![wf_dashboard](https://user-images.githubusercontent.com/14773203/58694469-54f0a900-8393-11e9-9501-3f1c18c3e040.png)
![wf_orders](https://user-images.githubusercontent.com/14773203/58694470-55893f80-8393-11e9-885b-0008a2bd97ba.png)
![wf_ordersSelected](https://user-images.githubusercontent.com/14773203/58694471-5621d600-8393-11e9-932d-e7bb4b478676.png)

**Comment by marb2000** [comment]
Hey @jaenfourie, 

These designs are amazing, I really appreciate your time and effort to design this. I'm sure that there will be a lot of ideas we can take from it in the future.

Best regards
-Miguel

**Comment by JuandreG** [comment]
Where can I find this? This looks amazing.

**Comment by mdtauk** [comment]
I guess the upcoming "Sun Valley" UI changes, with WinUI 2.6/3.0 controls - may need a change to the samples and some call outs for new approaches to things like list views to cards.
